---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
        - apt::default
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[wp::default]
    attributes:
